#!/bin/bash

# This file goes in /usr/local/bin/ and should be named m2k_notify
# This file is a modified version of librarian-notify-send.
# Which in turn is a modified version of alt-notify-send. It has
# been modified to send images with the notifications.
# For usage see:
#    http://xbmc.org/wiki/?title=MythicalLibrarian#GNOME_Desktop_Notifications

#TODO: Categories, from http://www.galago-project.org/specs/notification/0.9/x211.html
# "transfer" A generic file transfer or download notification that doesn't fit into any other category.
# "transfer.complete"     A file transfer or download complete notification.
# "transfer.error"        A file transfer or download error.
# "network"  A generic network notification that doesn't fit into any other category.
# "network.connected"     A network connection notification, such as successful sign-on to a network service. This should not be confused with device.added for new network devices.
# "network.disconnected"  A network disconnected notification. This should not be confused with device.removed for disconnected network devices.
# "network.error" A network-related or connection-related error. 

user="$(whoami)"
pids="$(pgrep -u $user gnome-session)"
title="$1"
text="$2"
image="$3"

[[ -z "$title" ]] && printf '%s\n' 'You need to give me a title' >&2 && exit 1

[[ -z "$text" ]] && text=$title

#TODO: this isn't used... #NOTE: Ubuntu's Notify OSD and GNOME Shell both ignore this parameter.
if [ -z "$timeout" ]; then
  #timeout=6000    #6 seconds
  #timeout=60000   #1 minute
  #timeout=180000  #3 minutes
  timeout=1800000 #30 minutes
fi

for pid in $pids; do
  # find DBUS session bus for this session
  DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$pid/environ | sed -e 's/DBUS_SESSION_BUS_ADDRESS=//')
  # send message to DBUS
  DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS notify-send -u low -i "$image" "$title" "$text"
  #DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS notify-send --app-name=Kodi -t $timeout -u low -i "$image" "$title" "$text"
done
